language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: "G7rwDwvfBwyuYTZJBkAiFY/MpodVayPqTzcIiyT3lS03Z7m7aUrg+7m2uxW9ldAIxGBhXN4nhNuFvYyMAJAkGaBh7ub3xZusTNtlrGD0eMvJHbMdN5kMbiDgfHwqbZ1l9gmHwSiSFYjnPyA0J8QGxwhaOh9GKXsFqJFdy8rmiIYAmjEVHG44lJ6HUuuJbi4lKpamxxQyd+K5DNgUJrGcltWWdyEw3YTxYjft745UwPLFq9d3R7QDmucrWDFajXPEkxzgNSFPgP7r7/q2s3srI3vY1jfDmk1Y8xobxUXGLJsOvK9uIy8uAQrpCKM+E8aWtzX71HkKaqZRWDH/zg8oUfKasgpJVQdi4OLB2ch7aPTTuzgaYUw1ByE4j1hJsYu0MBZTWCMIQUKhu1Ag36/kqts9wAbmj9OtdAllGXWHuiOP8XY0NkP0GzCltVFHpnJeEZ4BV6fA2sjXRO8a6n5jIkXuAyYkaMHf5nk9BXgJ7w+v9C0Z3cvh0X+Ahwizdf8lLpTTr/ezUSrKSqOG3dajHQx0WsUgVdAM5PCeCSacEBdi6iNzuhi4pA1ruB4cWEaiPy/K0PW6uq4vUOtSlA2Ft7gY2CNGnVvWoR0UUAIomGjChyphT/Ld6w82EtM5njDWQpKC6LfSYVDa5huRSVCka2uGq2d4dxEVtxtBOlBE/HY="
  app: 'safe-earth-19588'
  on:
    repo: Aaron-Lathrop/react-trello-testing
